function [fitresult, gof] = HgFit(Hg_mean, Hg_theoretical)
%CREATEFIT(HG_MEAN,HG_THEORETICAL)
%  Create a fit.
%
%  Data for 'Hg Data' fit:
%      X Input : Hg_mean
%      Y Output: Hg_theoretical
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Mar-2017 14:32:00


%% Fit: 'Hg Data'.
[xData, yData] = prepareCurveData( Hg_mean, Hg_theoretical );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'Hg Data' );
h = plot( fitresult, xData, yData );
legend( h, 'Hg_theoretical vs. Hg_mean', 'Hg Data', 'Location', 'NorthEast' );
% Label axes
xlabel Hg_mean
ylabel Hg_theoretical
grid on


